services:
  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis
    volumes:
      - .:/usr/src/app


  mongodb:
    image: mongo:6
    container_name: db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
  seed:
    build: .
    command: ["node", "seed.js"]
    depends_on:
      - app
      - mongodb

volumes:
  mongo_data:
