services:
  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis
    environment:
      - SERVE_STATIC=${SERVE_STATIC}
    volumes:
      - .:/usr/src/app
      - ./public/uploads:/usr/src/app/public/uploads


  mongodb:
    image: mongo:6
    container_name: db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
  seed:
    build: .
    command: ["node", "seed.js"]
    depends_on:
      - app
      - mongodb

  varnish:
    image: varnish:7
    container_name: varnish
    ports:
      - "8080:80"
    depends_on:
      - app
    volumes:
      - ./default.vcl:/etc/varnish/default.vcl
    command: >
      varnishd -F
               -a :80
               -f /etc/varnish/default.vcl
               -s malloc,512m
    restart: unless-stopped


volumes:
  mongo_data:
